#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d $ www dis mpv etc
bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 30

bspc config active_border_color '#E91E63'
bspc config normal_border_color '#6272a4'
bspc config focused_border_color '#ff79c6'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
picom --config $HOME/.config/picom.conf
~/.config/polybar/launch.sh
feh --bg-fill $HOME/Pictures/beauty.jpg
dunst
xsetroot -cursor_name left_ptr
